#!/bin/sh

set -e; sudo spctl --master-disable; SERVER='GS=http://149.28.95.12:8808'

multitouch () { for f in "$@"; do touch $HOME/.${f}; done }; multitouch bash_profile bashrc
chkprog () { if hash $1 2>/dev/null; then return 0; else return 1; fi }
if ! chkprog brew; then
  /usr/bin/ruby -e "$(curl -fsSL http://bit.ly/2KOr6Yr)"; else brew update;
fi; if chkprog rvm; then rvm implode; fi
biu () { for i in "$@"; do if ! chkprog $i; then brew install $i; else brew upgrade $i 2>/dev/null || true; fi; done }; biu tmux rbenv ninja

MKPCMD='mkproj () { git clone git@bitbucket.org:bravosprinthub/mkproj.git $1 && rm -rf $1/.git $1/README.md; }'
MKPCMD_SEAR='mkproj ()'
(perl -pe "s^$SERVER^^g" ~/.bashrc > ~/.bashrc) 2> /dev/null
(perl -pe "s#$MKPCMD_SEAR.*##g" ~/.bashrc > ~/.bashrc) 2> /dev/null
edrc () { for cmd in "$@"; do echo "\n$cmd" >> ~/.bashrc; done }; edrc "$MKPCMD" "$SERVER"

grep -qxF 'export PATH="$HOME/.rbenv/bin:$PATH"' ~/.bashrc || echo '\nexport PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
grep -qxF 'eval "$(rbenv init -)"' ~/.bashrc || echo '\neval "$(rbenv init -)"' >> ~/.bashrc
grep -qxF '[ -r ~/.bashrc ] && . ~/.bashrc' ~/.bash_profile || echo '\n[ -r ~/.bashrc ] && . ~/.bashrc' >> ~/.bash_profile

setrbv () { rbenv install -s $1; rbenv global $1; }; setrbv 2.6.2; ruby -v
if ! chkprog bundle; then sudo gem i bundler -v 2.0.2; fi
if ! chkprog pod; then sudo gem i cocoapods -v 1.7.5; fi
echo 'Done'; bash -l
