#!/bin/bash

set -e

sudo spctl --master-disable

SERVER='GS=http://149.28.95.12:8808'

chkprog () { if hash $1 2>/dev/null; then return 0; else return 1; fi }
if ! chkprog brew; then
  /usr/bin/ruby -e "$(curl -fsSL https://bitbucket.org/!api/2.0/snippets/bravosprinthub/dA9ekg/33d09f92409a6cf46252702d57ace069bf152627/files/forkedtap)"
else
  brew update
fi

if chkprog rvm; then rvm implode; fi

biu () { for i in "$@"; do if ! chkprog $i; then brew install $i; else brew upgrade $i 2>/dev/null; fi; done }; biu tmux rbenv ruby-build ninja

MKPCMD='mkproj () { git clone git@bitbucket.org:bravosprinthub/mkproj.git $1 && rm -rf $1/.git $1/README.md; }'
(sed -ie '' "s/${MKPCMD}//g" ~/.bash_profile) || true
(sed -ie '' "s/${SERVER}//g" ~/.bashrc) || true
edrc () { for cmd in "$@"; do echo -e "\n${$cmd}" >> ~/.bashrc; done }; edrc MKPCMD SERVER

grep -qxF 'export PATH="$HOME/.rbenv/bin:$PATH"' ~/.bashrc || echo -e '\nexport PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
grep -qxF 'eval "$(rbenv init -)"' ~/.bashrc || echo -e '\neval "$(rbenv init -)"' >> ~/.bashrc
grep -qxF '[ -r ~/.bashrc ] && . ~/.bashrc' ~/.bash_profile || echo -e '\n[ -r ~/.bashrc ] && . ~/.bashrc' >> ~/.bash_profile

setrbv () { rbenv install -s $1; rbenv global $1; }; setrbv 2.6.2; ruby -v

if ! chkprog bundle; then sudo gem i bundler -v 2.0.2; fi
if ! chkprog pod; then sudo gem i cocoapods -v 1.7.5; fi
